services:
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: seo_compass
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # web:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - redis
  #   volumes:
  #     - .:/app
  #   command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  worker:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
    command: celery -A app.tasks.celery_app worker --loglevel=info

# volumes:
#   postgres_data:
